low:
    - rule:
        cwe_ids:
            - "346"
        id: javascript_express_origin_validation_error
        description: Missing validation of origin detected.
        documentation_url: https://docs.bearer.com/reference/rules/javascript_express_origin_validation_error
      line_number: 5
      filename: no_origin_validation_in_cors_config.js
      parent_line_number: 5
      parent_content: |-
        app.use(
          cors({
            methods: ['GET'],
            origin: "*"
          })
        )
    - rule:
        cwe_ids:
            - "346"
        id: javascript_express_origin_validation_error
        description: Missing validation of origin detected.
        documentation_url: https://docs.bearer.com/reference/rules/javascript_express_origin_validation_error
      line_number: 12
      filename: no_origin_validation_in_cors_config.js
      parent_line_number: 12
      parent_content: app.use(cors())


